version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: container-mysql-vollmed-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed_api
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306   # HOST:CONTAINER
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
